# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
      options = [ "subvol=@varlib" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
      options = [ "subvol=@varlog" ];
    };

  fileSystems."/mnt/btr_pool" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2F52-C8E4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/urie/app" =
    { device = "/dev/disk/by-uuid/d30eb1e9-f993-4657-8c24-8eabe3005091";
      fsType = "btrfs";
      options = [ "subvol=@mydata" ];
    };

  fileSystems."/mnt/btr_backup" =
    { device = "/dev/disk/by-uuid/fd34c28c-d7bf-435e-a2c5-0875502391b5";
      fsType = "btrfs";
      options = [ "subvol=@backup" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d5e0addb-684d-401b-a5ce-7ea95d4c4d27"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp200s0f4u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tun0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
