{
  flake.wrappers.pi-base =
    {
      config,
      wlib,
      lib,
      pkgs,
      ...
    }:
    let
      jsonFmtType = wlib.types.structuredValueWith { typeName = "JSON"; };
    in
    {
      imports = [ wlib.modules.default ];

      options = {
        settings = lib.mkOption {
          type = jsonFmtType;
          default = { };
        };
        models = lib.mkOption {
          type = jsonFmtType;
          default = { };
        };
        keybindings = lib.mkOption {
          type = jsonFmtType;
          default = { };
        };

        generatedConfig.output = lib.mkOption {
          type = lib.types.str;
          default = config.outputName;
          description = ''
            The derivation output for the config generated by this wrapper module
          '';
        };

        generatedConfig.placeholder = lib.mkOption {
          type = lib.types.str;
          default = "${placeholder config.generatedConfig.output}/${config.binName}-config";
          readOnly = true;
          description = ''
            The placeholder accessible in the wrapper derivation build script for the config generated by this wrapper module
          '';
        };

        themeFile = lib.mkOption {
          type = lib.types.nullOr lib.types.path;
          default = null;
        };

        skills = lib.mkOption {
          type = lib.types.attrsOf wlib.types.stringable;
          default = { };
        };
      };

      config =
        let
          themeName = builtins.head (builtins.match "(.*)\\.json" (builtins.baseNameOf config.themeFile));
        in
        {
          package = lib.mkDefault pkgs.pi-coding-agent;
          envDefault = lib.mkDefault {
            PI_OFFLINE = "1";
            PI_TELEMETRY = "0";
            PI_SKIP_VERSION_CHECK = "1";
          };
          constructFiles =
            (builtins.mapAttrs
              (n: v: {
                relPath = "${config.binName}-config/${n}.json";
                content = builtins.toJSON v;
              })
              {
                inherit (config) settings models keybindings;
              }
            )
            // (builtins.mapAttrs (n: v: {
              relPath = "${config.binName}-config/skills/${n}";
              builder = "cp -R ${v} \"$2\"";
            }) config.skills)
            // (lib.optionalAttrs (config.themeFile != null) {
              theme = {
                relPath = "${config.binName}-config/themes/${themeName}.json";
                builder = "cp ${config.themeFile} \"$2\"";
              };
            });

          settings =
            { }
            // (lib.optionalAttrs (config.themeFile != null) {
              theme = themeName;
            });

          runShell = [
            ''
              export PI_CODING_AGENT_DIR="$HOME/.config/${config.binName}/agent"
              mkdir -p "$PI_CODING_AGENT_DIR"
              ln -sfn ${config.generatedConfig.placeholder}/settings.json "$PI_CODING_AGENT_DIR/settings.json"
              ln -sfn ${config.generatedConfig.placeholder}/models.json "$PI_CODING_AGENT_DIR/models.json"
              ln -sfn ${config.generatedConfig.placeholder}/keybindings.json "$PI_CODING_AGENT_DIR/keybindings.json"
              ln -sfn ${config.generatedConfig.placeholder}/themes "$PI_CODING_AGENT_DIR/themes"
              ln -sfn ${config.generatedConfig.placeholder}/skills "$PI_CODING_AGENT_DIR/skills"
            ''
          ];

          flags = {
            "--tui-mode" = "fullscreen";
          };
        };
    };
}
